---
pagetitle: "Nathanael Rolim"
output: 
  pagedown::html_resume:
    self_contained: false
    css: ['assets/css/resume.css', 'assets/css/overwrite.css']
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(magrittr) # For the pipe
source("./resume.R")
```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

```{r, echo=FALSE}
print_contact()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated on `r Sys.Date()`.


Main
================================================================================

Nathanael Rolim {#title}
--------------------------------------------------------------------------------

Please note that this is a *real* resume, and I'm really looking for a PhD
student position at the moment. I made this resume because Yihui asked me
if I'd like to test the **pagedown** package with my resume. If you are
interested in my background and skills, please feel free to contact me.


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r, echo=FALSE}
print_section("education")
```


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r, echo=FALSE}
print_section("experience")
```


Other Works {data-icon=hands-helping}
--------------------------------------------------------------------------------

```{r, echo=FALSE}
print_section("extra")
```


Awards and Certifications {data-icon=award}
--------------------------------------------------------------------------------

```{r, echo=FALSE}
print_section("awards")
```