on:
  push:
  schedule:
    - cron: "0 12 15,30 * *"

name: "Build CV"

jobs:
  build-cv:
    name: Build Resume
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: $({ secrets.GITHUB_TOKEN })
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          use-public-rspm: true
      
      - name: Install dependencies
        run: |
          install.packages(c('googlesheets4','stringr','dplyr','lubridate','glue','rmarkdown','pagedown'))
        shell: Rscript {0}

      - name: Render document
        run: |
          rmarkdown::render('index.Rmd')
        shell: Rscript {0}

      - name: Create final folder
        run: |
          mkdir output
          mv index.html output
          mv index_files output
          mv assets output
      
      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: output
